# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 481df42a915f8d1044cfbc28a4b713c15312b784ced142ff2675f8d7d31e709b29473d91ab5c88c6a22c8a45143323613cad0fd30ee53ebb7a7307c48cb58601

test:
  secret_key_base: 72f5d9f34ff9a8465dbf774ce2ecab448e7ec4b7de5bcb85ca5899819f31a279adadbf4701088be4a8585aeb3fe9be31b4b677e153a08492765cdedb86893bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
