# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  $grid = $('.container')
  $grid.isotope itemSelector: '.element-item'
  filters = []
  # A convenient bucket for all the filter options, 
  # just so we don't have to look them up in the DOM every time.
  # (a global array is maybe sort of not the most elegant 
  # way you could deal with this but you get the idea.)
  # Search event handlers

  $('.image').click ->
    $('#pepsico').show()
    $('#loreal').hide()
    return

  $('#back').click ->
    $('#pepsico').hide()
    $('#loreal').show()
    

  $('.quicksearch').on 'keyup', ->
    # debounce removed for brevity, but you'd put it here
    filters[0] = @value
    console.log("VALUE", @value)
    runFilter()
    return
  $('.filter-btn').on 'click', ->
    filters[1] = @value
    runFilter()
    return
  # and so on if more filters needed
  # The filter itself

  runFilter = ->
    $grid.isotope filter: ->
      if filters[0]
        # at least some search text was entered:
        qsRegex = new RegExp(filters[0], 'gi')
        # if the title doesn't match, eliminate it:
        if !$(this).find('.title').text().match(qsRegex)
          return false
      if filters[1]
        # a category was selected; filter out others:
        if !$(this).hasClass(filters[1])
          return false
      # etcetera, for any other filters 
      # successfully passed all conditions, so:
      true
    return

  return


    



# ---
# generated by js2coffee 2.2.0